name: Auto Download YouTube & Update Playlist

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Video Link'
        required: true
        type: string

permissions:
  contents: write

jobs:
  download_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          sudo pip3 install --break-system-packages -U yt-dlp

      - name: Download HD Video (Bypass Bot Check)
        run: |
          mkdir -p videos
          # iOS ও Mobile Web ক্লায়েন্ট দিয়ে ইউটিউব বট ব্লক বাইপাস
          yt-dlp \
            --extractor-args "youtube:player_client=ios,mweb" \
            -f "best[ext=mp4]/best" \
            --no-check-certificates \
            -o "videos/stream.mp4" "${{ inputs.youtube_url }}"

      - name: Update Playlist
        run: |
          echo "videos/stream.mp4" > playlist.txt

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add videos/stream.mp4 playlist.txt
          git commit -m "Auto updated video from YouTube" || echo "No changes"
          git push origin main
